name: Build, Package, Release
'on':
  release:
    types:
      - created
  push:
    branches:
      - main
env:
  VERSION: null
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: releaseWithMogenius-4c3c50d2cd2bef8e1b5d
        name: Release with mogenius
        uses: mogenius/mogenius-release-action@v1
        with:
          dev: true
          image: ${{ vars.MO_IMAGE_NAME__MAIN }}:${{ env.VERSION }}
          kind: Deployment
          namespace: my-namespace2
          resourceName: test006
          containerName: test006
          keyKind: ${{ vars.MO_API_KIND__MAIN }}
          token: ${{ secrets.MO_API_TOKEN__4c3c50d2cd2bef8e1b5d__MAIN }}
